services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chatapp_rabbitmq
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guestt}
    networks:
      - chatapp_network

  auth-db:
    image: mysql:8.0
    container_name: chatapp_auth_db
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME:-chatapp_auth_service}
      MYSQL_USER: ${AUTH_DB_USER:-chatapp_auth_user}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD:-root_password}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD:-chatapp_auth_password}
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    ports:
      - '${AUTH_DB_PORT:-3306}:3306'
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - chatapp_network

  user-db:
    image: postgres:13
    container_name: chatapp_user_db
    environment:
      POSTGRES_DB: ${USER_DB_NAME:-chatapp_user_service}
      POSTGRES_USER: ${USER_DB_USER:-chatapp_user}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-chatapp_password}
    ports:
      - '${USER_DB_PORT:-5432}:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - chatapp_network

volumes:
  auth_db_data:
  user_db_data:

networks:
  chatapp_network:
    driver: bridge
